### ISSUE TITLE
Will you update this repo?

### ISSUE THREAD

**Issue by LitvK** [Qrilee/JustInMind_Crack#4]
Do you plan to update your beautiful software to 8.2 version?

**Comment by Qrilee** [comment]
sorry , the newest software had using the zelix obfuscator (maybe the strongest java obfuscator)

by the way , i think use fake time to crack it may be better

**Comment by LitvK** [comment]
Thanks. They should store installation date somewhere. Will try to find.

**Comment by Qrilee** [comment]
it verified the license through netwok，
